"""knowledge passages with pgvector embeddings

Hand-written rather than autogenerated: the embedding column differs by dialect
(a real `vector` on PostgreSQL, JSON elsewhere), and the extension and the
nearest-neighbour index only exist on PostgreSQL.

Revision ID: 15bf02cfcb80
Revises: e72830eaedfa
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "15bf02cfcb80"
down_revision: Union[str, None] = "e72830eaedfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIM = 1024


def upgrade() -> None:
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    if is_postgres:
        # Requires an image with pgvector available (pgvector/pgvector:pg16).
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        embedding_type: sa.types.TypeEngine = sa.dialects.postgresql.ARRAY(sa.Float)
        from pgvector.sqlalchemy import Vector

        embedding_type = Vector(EMBEDDING_DIM)
    else:
        embedding_type = sa.JSON()

    op.create_table(
        "knowledge_passages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("passage_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column("embedding_dim", sa.Integer(), nullable=True),
        sa.Column("embedding", embedding_type, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_knowledge_passage_key", "knowledge_passages", ["passage_key"], unique=True)
    op.create_index("ix_knowledge_model", "knowledge_passages", ["embedding_model"])
    op.create_index(
        op.f("ix_knowledge_passages_created_at"), "knowledge_passages", ["created_at"]
    )

    if is_postgres:
        # IVFFlat trades a little recall for a large speed gain. `lists` is
        # deliberately small: it should be about sqrt(rows), and this corpus is
        # in the low thousands. Revisit it if the corpus grows by an order of
        # magnitude. The index is only used once the table has data, so building
        # it here is cheap.
        op.execute(
            "CREATE INDEX ix_knowledge_embedding_cosine "
            "ON knowledge_passages USING ivfflat (embedding vector_cosine_ops) "
            "WITH (lists = 40)"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_knowledge_embedding_cosine")

    op.drop_index(op.f("ix_knowledge_passages_created_at"), table_name="knowledge_passages")
    op.drop_index("ix_knowledge_model", table_name="knowledge_passages")
    op.drop_index("ix_knowledge_passage_key", table_name="knowledge_passages")
    op.drop_table("knowledge_passages")
    # The extension is left in place: other tables or databases may use it, and
    # dropping it is not this migration's business.
