"""initial schema

Revision ID: e72830eaedfa
Revises: 
Create Date: 2026-09-02 10:32:55.032130
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e72830eaedfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'CLINICIAN', 'ADMIN', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('patient_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('primary_condition', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('resting_hr_baseline', sa.Integer(), nullable=True),
    sa.Column('target_hr_max', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_profiles_clinician_id'), ['clinician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('conversations',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_conversations_patient_created', ['patient_id', 'created_at'], unique=False)

    op.create_table('exercise_plans',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('prescribed_by_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('minutes_per_session', sa.Integer(), nullable=False),
    sa.Column('target_exertion_max', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_plans_patient_active', ['patient_id', 'is_active'], unique=False)

    op.create_table('risk_flags',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('VITALS', 'SYMPTOM', 'SESSION', name='flagsource', native_enum=False, length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('rule_code', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', name='severity', native_enum=False, length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='flagstatus', native_enum=False, length=20), nullable=False),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.create_index('ix_flags_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index('ix_flags_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_rule_code'), ['rule_code'], unique=False)

    op.create_table('symptom_reports',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', name='severity', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptom_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_symptoms_patient_recorded', ['patient_id', 'recorded_at'], unique=False)

    op.create_table('vitals_records',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vitals_records', schema=None) as batch_op:
        batch_op.create_index('ix_vitals_patient_recorded', ['patient_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vitals_records_created_at'), ['created_at'], unique=False)

    op.create_table('exercise_sessions',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity', sa.String(length=120), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['exercise_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_sessions_patient_performed', ['patient_id', 'performed_at'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('transcribed_from_audio', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index('ix_messages_conversation_created')

    op.drop_table('messages')
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_patient_performed')
        batch_op.drop_index(batch_op.f('ix_exercise_sessions_created_at'))

    op.drop_table('exercise_sessions')
    with op.batch_alter_table('vitals_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vitals_records_created_at'))
        batch_op.drop_index('ix_vitals_patient_recorded')

    op.drop_table('vitals_records')
    with op.batch_alter_table('symptom_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_symptoms_patient_recorded')
        batch_op.drop_index(batch_op.f('ix_symptom_reports_created_at'))

    op.drop_table('symptom_reports')
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_flags_rule_code'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_created_at'))
        batch_op.drop_index('ix_flags_status_created')
        batch_op.drop_index('ix_flags_patient_status')

    op.drop_table('risk_flags')
    with op.batch_alter_table('exercise_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_plans_patient_active')
        batch_op.drop_index(batch_op.f('ix_exercise_plans_created_at'))

    op.drop_table('exercise_plans')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_patient_created')
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_patient_profiles_created_at'))
        batch_op.drop_index(batch_op.f('ix_patient_profiles_clinician_id'))

    op.drop_table('patient_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
